<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Barang;
use App\Models\Kategori;
use Carbon\Carbon;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sampleMedicines = [
            [
                "drugName" => "Atorvastatin",
                "image" => "https://cdn01.pharmeasy.in/dam/products/J21424/atorvastatin-10-mg-tablet-10-medlife-pure-generics-combo-3-1626532296.jpg",
                "description" => "Used to lower cholesterol and triglyceride levels.",
                "expirydate" => "2025-1-15",
                "price" => 60000,
                "category" => "HMG-CoA reductase inhibitors, or statins.",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Amoxicillin",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/8/332350358/SI/JT/VF/98283251/amoxicillin-drugs3.jpg",
                "description" => "Antibiotic used to treat bacterial infections.",
                "expirydate" => "2024-12-01",
                "price" => 62000,
                "category" => "antibiotics",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Lisinopril",
                "image" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRquzMUwap3aIcmZQhZ4FOztWQorUZSonP4wg&s",
                "description" => "Treats high blood pressure and heart failure.",
                "expirydate" => "2025-06-30",
                "price" => 40000,
                "category" => "blood pressure",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Metformin",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/8/332774949/NY/WA/ZJ/6299000/metformin-hydrochloride-tablets.jpeg",
                "description" => "Used to control blood sugar levels in type 2 diabetes.",
                "expirydate" => "2025-04-10",
                "price" => 31000,
                "category" => "Diabetes",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Omeprazole",
                "image" => "https://5.imimg.com/data5/JD/FH/VU/SELLER-5478572/omeprazole-capsules-20mg.jpeg",
                "description" => "Treats gastroesophageal reflux disease (GERD).",
                "expirydate" => "2024-09-20",
                "price" => 75000,
                "category" => "gastroesophageal",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Amlodipine",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/1/CP/LY/QV/88793954/amlodipine-tablets-ip.jpeg",
                "description" => "Used to treat high blood pressure and angina.",
                "expirydate" => "2025-08-15",
                "price" => 20000,
                "category" => "blood pressure",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Zolpidem",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/9/342848763/LR/GK/WN/197293575/zolpidem-10-mg-tablet.jpg",
                "description" => "Treats insomnia.",
                "expirydate" => "2024-11-30",
                "price" => 70000,
                "category" => "Insomnia",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Clonazepam",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2021/5/CR/QB/QR/3184985/clonvul0-5.jpg",
                "description" => "Used to treat seizure and panic disorders.",
                "expirydate" => "2025-05-10",
                "price" => 350000,
                "category" => "depression",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Montelukast",
                "image" => "https://www.glamrisdermacare.com/wp-content/uploads/2021/08/0000s_0006_BILAZIL-M-min.jpg",
                "description" => "Used to treat allergies and prevent asthma attacks.",
                "expirydate" => "2024-12-05",
                "price" => 150000,
                "category" => "allergy",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Gabapentin",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/5/311267943/ZR/MT/QJ/69086821/gabapentin-100mg-tablet-500x500.jpg",
                "description" => "Used to treat nerve pain and seizures.",
                "expirydate" => "2025-07-25",
                "price" => 131000,
                "category" => "anticonvulsants",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Albuterol",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/8/337313153/HK/FV/II/57623134/buy-albuterol-hfa-90-mcg-inhaler-online.jpg",
                "description" => "Used to treat bronchospasm.",
                "expirydate" => "2024-10-10",
                "price" => 34000,
                "category" => "Inhaler",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Loratadine",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/8/332709645/ER/VU/LD/6299000/loratadine-10-mg-tablets.jpeg",
                "description" => "Antihistamine used to relieve allergy symptoms.",
                "expirydate" => "2025-03-01",
                "price" => 62000,
                "category" => "Antihistamine",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Ibuprofen",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/6/319597573/MH/NE/SR/135658020/ibuprofen-400-mg-bp-tablets.jpg",
                "description" => "Used to reduce fever and treat pain or inflammation.",
                "expirydate" => "2025-09-15",
                "price" => 70000,
                "category" => "inflammatory",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Warfarin",
                "image" => "https://www.careformulationlabs.com/uploaded_files/warfarin-5.png",
                "description" => "Used to prevent blood clots.",
                "expirydate" => "2025-02-28",
                "price" => 71000,
                "category" => "blood pressure",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Cetirizine",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/5/311971664/FU/KT/PV/11858298/cetirizine-tablet.webp",
                "description" => "Antihistamine used to treat allergy symptoms.",
                "expirydate" => "2025-05-15",
                "price" => 26000,
                "category" => "Antihistamine",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Sertraline",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/8/337366367/KI/RJ/BA/7034457/sertraline-100-mg-tablets.jpg",
                "description" => "Antidepressant used to treat depression and anxiety.",
                "expirydate" => "2025-06-10",
                "price" => 260000,
                "category" => "depression",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Tramadol",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/8/331683629/YW/EW/FV/1359917/tramadol-hydrochloride-paracetamol-tablets.jpg",
                "description" => "Used to treat moderate to severe pain.",
                "expirydate" => "2025-08-20",
                "price" => 17000,
                "category" => "Pain Killer",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Tamsulosin",
                "image" => "https://5.imimg.com/data5/GLADMIN/Default/2024/1/382027832/MW/YF/DV/37869803/tamsulosin-hydrochloride-tablet.png",
                "description" => "Used to treat symptoms of an enlarged prostate.",
                "expirydate" => "2025-04-05",
                "price" => 85000,
                "category" => "Gynaecology",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Oxycodone",
                "image" => "https://tajgenerics.com/wp-content/uploads/cache/images/Oxycodone_7_5mg__Acetaminophen_375mg_Tablet_Exporters-scaled/Oxycodone_7_5mg__Acetaminophen_375mg_Tablet_Exporters-scaled-3481289551.jpg",
                "description" => "Used to treat moderate to severe pain.",
                "expirydate" => "2025-07-30",
                "price" => 230000,
                "category" => "Pain Killer",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Prednisone",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2022/12/CE/BE/CW/23808697/prednisone-500x500.JPG",
                "description" => "Corticosteroid used to treat inflammation.",
                "expirydate" => "2025-09-01",
                "price" => 12000,
                "category" => "corticosteroid",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Fluoxetine",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2022/9/GN/LY/IE/154048565/fluoxetine-10mg-tablet.png",
                "description" => "Antidepressant used to treat depression and OCD.",
                "expirydate" => "2025-10-10",
                "price" => 442000,
                "category" => "depression",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Metoprolol",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2022/11/UO/RS/FG/161638739/metoprolol-tartrate-50-mg.jpg",
                "description" => "Used to treat high blood pressure and angina.",
                "expirydate" => "2025-02-15",
                "price" => 48000,
                "category" => "blood pressure",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Furosemide",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/8/333795220/XM/UX/IJ/6299000/furosemide-tablet.jpeg",
                "description" => "Diuretic used to treat fluid retention and swelling.",
                "expirydate" => "2025-05-25",
                "price" => 14000,
                "category" => "loop diuretics",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Duloxetine",
                "image" => "https://5.imimg.com/data5/AL/LG/MY-6299000/duloxetine-30-mg-capsules.jpg",
                "description" => "Used to treat depression and anxiety.",
                "expirydate" => "2025-11-05",
                "price" => 100000,
                "category" => "depression",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Simvastatin",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/10/357085613/HL/RR/GE/50963842/simvastatin-tablet-ups-20-mg.jpg",
                "description" => "Used to lower cholesterol and triglycerides.",
                "expirydate" => "2025-08-10",
                "price" => 100000,
                "category" => "cholesterol",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Losartan",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/12/373066330/IL/GL/IT/180648134/losartan-potassium-tablets-ip-500x500.jpg",
                "description" => "Used to treat high blood pressure.",
                "expirydate" => "2025-01-25",
                "price" => 38000,
                "category" => "blood pressure",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Clopidogrel",
                "image" => "https://5.imimg.com/data5/SELLER/Default/2023/3/293106006/NJ/NS/EB/29765627/clopidogrel-75mg-aspirin-75mg-tab-500x500.jpg",
                "description" => "Used to prevent blood clots.",
                "expirydate" => "2025-03-20",
                "price" => 54000,
                "category" => "antiplatelet",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Hydrocodone",
                "image" => "https://t4.ftcdn.net/jpg/02/93/25/13/360_F_293251390_jBCMpaDN1V1ipxcqpthTt3yikZPAZMr8.jpg",
                "description" => "Used to treat severe pain.",
                "expirydate" => "2025-07-05",
                "price" => 259000,
                "category" => "Pain Killer",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Trazodone",
                "image" => "https://c8.alamy.com/comp/GJ7J4D/molipaxin-100mg-capsules-antidepresant-trazodone-hydrochloride-GJ7J4D.jpg",
                "description" => "Antidepressant used to treat depression and insomnia.",
                "expirydate" => "2025-06-15",
                "price" => 185000,
                "category" => "Depression",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Ranitidine",
                "image" => "https://wellonapharma.com/admincms/product_img/product_actual_img/Ranitidine%20Tablets_27-01-2017-08:47:41.jpg",
                "description" => "Used to reduce stomach acid and treat ulcers.",
                "expirydate" => "2024-12-20",
                "price" => 30000,
                "category" => "H2 blockers",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Tazarotene",
                "image" => "https://tiimg.tistatic.com/fp/1/006/419/tazarotene-cream-0-1--641.jpg",
                "description" => "This medication is a retinoid, prescribed for psoriasis and acne. It may decrease skin inflammation and skin changes associated with psoriasis.",
                "expirydate" => "2025-02-02",
                "price" => 420000,
                "category" => "Dermatology",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Isotretinoin",
                "image" => "https://i.postimg.cc/D0VJ7Lr1/iso.jpg",
                "description" => "This medication is a retinoid, prescribed for acne and other skin disorders. It reduces skin oil production, changing the characteristics of the skin oil, and preventing abnormal hardening of the skin.",
                "expirydate" => "2025-12-23",
                "price" => 299000,
                "category" => "Dermatology",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Minocycline",
                "image" => "https://i.postimg.cc/JhvtQZdS/mino.png",
                "description" => "Minocycline is a broad spectrum tetracycline antibiotic. It acts by inhibiting the growth of bacteria in the body, It may be effective in other infections as well, however several bacteria have developed resistance to the drug, It may be used in patients who are allergic to the penicillin group of drugs as an alternative.",
                "expirydate" => "2025-02-02",
                "price" => 300000,
                "category" => "Dermatology",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Calamine Lotion",
                "image" => "https://i.postimg.cc/L6x9TjJv/calamine.jpg",
                "description" => "This medication is an anti-itch medication that contains mixture of zinc oxide (ZnO) with about 0.5% iron (III) oxide, prescribed for itching skin conditions. This medication in some cases is used as a mild antiseptic to arrest infections caused by scratching the affected area. Calamine is proved to be an effective medication in acne treatment.",
                "expirydate" => "2025-12-23",
                "price" => 240000,
                "category" => "Dermatology",
                "countInStock" => 100,
            ],
            [
                "drugName" => "Dimethicone",
                "image" => "https://i.postimg.cc/K8K2DwSv/dim.jpg",
                "description" => "This medication is an emollient, prescribed for pediculosis, and other skin conditions.",
                "expirydate" => "2024-12-20",
                "price" => 220000,
                "category" => "Dermatology",
                "countInStock" => 100,
            ],
        ];

        foreach ($sampleMedicines as $item) {
            $categoryName = trim($item['category']);

            $kategori = Kategori::firstOrCreate(['nama_kategori' => $categoryName]);

            Barang::create([
                'kategori_id' => $kategori->id,
                'nama_barang' => $item['drugName'],
                'deskripsi'   => $item['description'],
                'gambar'      => $item['image'],
                'harga'       => $item['price'],
                'stok'        => $item['countInStock'],
                'expired_at'  => Carbon::parse($item['expirydate']),
            ]);
        }
    }
}
